### ISSUE TITLE
Unidentified Identifier after install

### ISSUE THREAD

**Issue by cworsley4** [libgit2/git2go#190]
Hi all,
I just installed git2go and when importing the package I get the below errors. Any suggestions here?

```
# github.com/libgit2/git2go
37: error: use of undeclared identifier 'git_cherrypick_init_options'; did you mean 'git_cherry_pick_init_options'?
37: error: use of undeclared identifier 'GIT_CHERRYPICK_OPTIONS_VERSION'
37: error: use of undeclared identifier 'git_cherrypick'; did you mean 'git_cherry_pick'?
37: error: use of undeclared identifier 'git_cherrypick_options'; did you mean 'git_cherry_pick_options'?
```

**Comment by b35li** [comment]
I guess you missed link to the libgit2. it looks like missing the source of c libraries.

**Comment by cworsley4** [comment]
I installed it using Homebrew on my Mac. I'm thinking it isn't installed in the right path?

**Comment by b35li** [comment]
I worked on rhel5 before, anyway, it doesn't matter. How did you installed? if you are under development, you can checkout to next and install it to test it. Then to fix the env issue, just my opinion.

**Comment by carlosmn** [comment]
As libgit2 doesn't provide a stable API across versions, you have to make sure you have installed the correct version of the libgit2 for git2go to work against. From this error, it looks like you have libgit2 v0.21 installed where git2go can find it, while git2go from `master` expects to work with libgit2 v0.22. Make sure you have the right version in the main `/usr/local/` paths.
