### ISSUE TITLE
This library does not work with libgit v1.2.0 when installed system-wide

### ISSUE THREAD

**Issue by lhchavez** [libgit2/git2go#834]
This is a known issue because there is a missing symbol:

```
go get github.com/libgit2/git2go/v32
go: downloading github.com/libgit2/git2go/v32 v32.0.4
go: downloading github.com/libgit2/git2go v27.10.0+incompatible
go: downloading golang.org/x/crypto v0.0.0-20201203163018-be400aefbc4c
go: downloading golang.org/x/sys v0.0.0-20201204225414-ed752295db88
# github.com/libgit2/git2go/v32
/usr/bin/ld: $WORK/b001/_x033.o: in function `_cgo_c4e5c3df4da7_Cfunc_git_remote_name_is_valid':
/tmp/go-build/cgo-gcc-prolog:517: undefined reference to `git_remote_name_is_valid'
collect2: error: ld returned 1 exit status
```
