### ISSUE TITLE
Allow libgit2 1.2.0

### ISSUE THREAD

**Issue by darix** [libgit2/git2go#775]
From a quick test, it seems that the code builds with 1.2.0

And if possible please tag a release with it so i can ask gitlab to pull that new version into gitaly.

Thank you in advance.

**Comment by lhchavez** [comment]
New tags that are forward-compatible with system-installed libgit2:

- v1.1.0-v1.2.x https://github.com/libgit2/git2go/releases/tag/v31.5.0
- v1.0.0-v1.2.x https://github.com/libgit2/git2go/releases/tag/v30.4.0

v32 is still not releasable since the dynamic version of libgit2 is missing one non-deprecated symbol, so keeping this issue open.

**Comment by darix** [comment]
Thank you

**Comment by marcelosousa** [comment]
After installing latest libgit2 v1.2.0, I'm getting the following error on go get:
```
go get github.com/libgit2/git2go/v32
go: downloading github.com/libgit2/git2go/v32 v32.0.4
go: downloading github.com/libgit2/git2go v27.10.0+incompatible
go: downloading golang.org/x/crypto v0.0.0-20201203163018-be400aefbc4c
go: downloading golang.org/x/sys v0.0.0-20201204225414-ed752295db88
# github.com/libgit2/git2go/v32
/usr/bin/ld: $WORK/b001/_x033.o: in function `_cgo_c4e5c3df4da7_Cfunc_git_remote_name_is_valid':
/tmp/go-build/cgo-gcc-prolog:517: undefined reference to `git_remote_name_is_valid'
collect2: error: ld returned 1 exit status
```

**Comment by lhchavez** [comment]
it's a known issue u_u

> v32 is still not releasable since the dynamic version of libgit2 is missing one non-deprecated symbol, so keeping this issue open.

i made the release anyways because folks that use the static (or bundled) library can still use it.
